[build]
  command = "npm install --omit=dev"
  functions = "netlify/functions"
  publish = "."

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[dev]
  command = "npm start"
  port = 3000
